apiVersion: v1
kind: Service
metadata:
  namespace: ns-elastic
  name: elasticsearch-master
  labels:
    app: elasticsearch
    role: master
spec:
  clusterIP: None
  selector:
    app: elasticsearch
    role: master
  ports:
    - port: 9200
      name: http
    - port: 9300
      name: node-to-node
---
apiVersion: v1
kind: Service
metadata:
  namespace: ns-elastic
  name: elasticsearch
  labels:
    app: elasticsearch
    role: data
spec:
  clusterIP: None
  selector:
    app: elasticsearch
    role: data
  ports:
    - port: 9200
      name: http
    - port: 9300
      name: node-to-node
---
apiVersion: v1
kind: Service
metadata:
  namespace: ns-elastic
  name: elasticsearch-service
  labels:
    app: elasticsearch
    role: master
spec:
  type: NodePort
  ports:
    - port: 9200
      targetPort: 9200
      nodePort: 29200
  selector:
    app: elasticsearch
    role: master
